Repository noodlemctwoodle/pf-azure-sentinel, pull requests merged in 2020-12, with the labels that each got.

#2 Update README.md
  Logstash-Configuration/README.md
Labels: documentation

#3 Various Updates
  Logstash-Configuration/README.md
  README.md
Labels: documentation

#4 Update 35-rules-desc.conf
  Logstash-Configuration/etc/logstash/conf.d/35-rules-desc.conf
Labels: bug

#5 Update and rename 07-interfaces.conf to 40-interfaces.conf
  Logstash-Configuration/etc/logstash/conf.d/40-interfaces.conf
Labels: enhancement

#7 Delete 05-firewall.conf
  Logstash-Configuration/etc/logstash/conf.d/05-firewall.conf
Labels: enhancement

#8 Update README.md
  Logstash-Configuration/README.md
Labels: enhancement
